ZadanieCoreMVC/Models/ErrorViewModel.cs
using System;

namespace ZadanieCoreMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ZadanieCoreMVC/Models/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Localization;

namespace ZadanieCoreMVC.Models
{
    public class UserViewModel
    {
        [Display(ResourceType = typeof(App_GlobalResources.GlobalResource), Name = "NickName")]
        [Required(ErrorMessageResourceType = typeof(App_GlobalResources.GlobalResource), ErrorMessageResourceName = "NickName_Is_Required", AllowEmptyStrings = false)]
        [RegularExpression(@"^[a-zA-Z]{1,30}$", ErrorMessageResourceType = typeof(App_GlobalResources.GlobalResource), ErrorMessageResourceName = "NickName_Is_Required")]
        public string NickName { get; set; }

        [Display(ResourceType = typeof(App_GlobalResources.GlobalResource), Name = "Email")]
        [Required(ErrorMessageResourceType = typeof(App_GlobalResources.GlobalResource), ErrorMessageResourceName = "Email_Is_Required", AllowEmptyStrings = false)]
        [EmailAddress(ErrorMessageResourceType = typeof(App_GlobalResources.GlobalResource), ErrorMessageResourceName = "Email_Format_Is_Incorrect")]
        public string Email { get; set; }
    }
}

ZadanieCoreMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ZadanieCoreMVC.Models;

namespace ZadanieCoreMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ZadanieCoreMVC/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ZadanieCoreMVC.Models;

namespace ZadanieCoreMVC.Controllers
{
    public class LoginController : Controller
    {
        public ActionResult Index()
        {
            return View("Login", new UserViewModel());
        }

        public ActionResult Summary(UserViewModel userViewModel)
        {
            return View(userViewModel);
        }

        public ActionResult Login(UserViewModel userViewModel)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction(nameof(Summary), userViewModel);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ZadanieCoreMVC/Controllers/SetLanguageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;

namespace ZadanieCoreMVC.Controllers
{
    public class SetLanguageController : Controller
    {
        [HttpPost]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

ZadanieCoreMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

ZadanieCoreMVC/Views/Login/Login.cshtml
@model ZadanieCoreMVC.Models.UserViewModel
@using ZadanieCoreMVC.App_GlobalResources

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Login", "Login", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(m => m.NickName)
                @Html.TextBoxFor(m => m.NickName)
                @Html.ValidationMessageFor(m => m.NickName, string.Empty, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Email)
                @Html.TextBoxFor(m => m.Email)
                @Html.ValidationMessageFor(m => m.Email, string.Empty, new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input type="submit" value="@GlobalResource.Save" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

ZadanieCoreMVC/Views/Login/Summary.cshtml
@model ZadanieCoreMVC.Models.UserViewModel
@using ZadanieCoreMVC.App_GlobalResources

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.LabelFor(m => m.NickName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NickName)
        </dd>
        <dt class="col-sm-2">
            @Html.LabelFor(m => m.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">@GlobalResource.Back</a>
</div>

ZadanieCoreMVC/Views/Shared/_Layout.cshtml
@using ZadanieCoreMVC.App_GlobalResources
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZadanieCoreMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            @await Html.PartialAsync("_SelectLanguagePartial")
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ZadanieCoreMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@GlobalResource.Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">@GlobalResource.Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ZadanieCoreMVC
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
@await Html.PartialAsync("_ValidationScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ZadanieCoreMVC/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LocOptions
@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div>
    <form class="form-inline" id="selectLanguage" asp-controller="SetLanguage" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" class="form-horizontal" role="form">
        <div class="input-group">
            <select class="custom-select" name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems" onchange="this.form.submit()"></select>
        </div>
    </form>
</div>